// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5SNtNf24FKIobsNOaSB4rIpjkUzD6d64',
    appId: '1:393634355857:web:66f3c7b509e7ae29593d30',
    messagingSenderId: '393634355857',
    projectId: 'smart-plant-pot-iot',
    authDomain: 'smart-plant-pot-iot.firebaseapp.com',
    databaseURL: 'https://smart-plant-pot-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-plant-pot-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQ0kaX3eZ59xlMAsw2FsnruPD50SOduQ',
    appId: '1:393634355857:android:bc5603c95b193ab5593d30',
    messagingSenderId: '393634355857',
    projectId: 'smart-plant-pot-iot',
    databaseURL: 'https://smart-plant-pot-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-plant-pot-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ_5QorK5LTIzk-ADhvpUt1BRaWWQd-_8',
    appId: '1:393634355857:ios:1dc012de3e8e909d593d30',
    messagingSenderId: '393634355857',
    projectId: 'smart-plant-pot-iot',
    databaseURL: 'https://smart-plant-pot-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-plant-pot-iot.firebasestorage.app',
    androidClientId: '393634355857-8boh84dig7a37s68r5kro9jss17uftna.apps.googleusercontent.com',
    iosClientId: '393634355857-jsj08b13bb5bmkeru9fv9qldgd1v36ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPlantPot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ_5QorK5LTIzk-ADhvpUt1BRaWWQd-_8',
    appId: '1:393634355857:ios:1dc012de3e8e909d593d30',
    messagingSenderId: '393634355857',
    projectId: 'smart-plant-pot-iot',
    databaseURL: 'https://smart-plant-pot-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-plant-pot-iot.firebasestorage.app',
    androidClientId: '393634355857-8boh84dig7a37s68r5kro9jss17uftna.apps.googleusercontent.com',
    iosClientId: '393634355857-jsj08b13bb5bmkeru9fv9qldgd1v36ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPlantPot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5SNtNf24FKIobsNOaSB4rIpjkUzD6d64',
    appId: '1:393634355857:web:7402a63593d630c9593d30',
    messagingSenderId: '393634355857',
    projectId: 'smart-plant-pot-iot',
    authDomain: 'smart-plant-pot-iot.firebaseapp.com',
    databaseURL: 'https://smart-plant-pot-iot-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-plant-pot-iot.firebasestorage.app',
  );

}